'use client';

import { useEffect } from 'react';
import { Users, Plus, X, UserCircle } from 'lucide-react';
import { useTranslation } from '@/i18n';
import { useSettlementStore } from '@/lib/store';
import { Card, CardHeader, CardTitle, CardAction, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';

export function MemberManager() {
  const { t } = useTranslation();
  const members = useSettlementStore((s) => s.members);
  const revenueAPercent = useSettlementStore((s) => s.revenueAPercent);
  const setRevenueAPercent = useSettlementStore((s) => s.setRevenueAPercent);
  const addMember = useSettlementStore((s) => s.addMember);
  const removeMember = useSettlementStore((s) => s.removeMember);
  const updateMember = useSettlementStore((s) => s.updateMember);

  const revenueBPercent = 100 - revenueAPercent;
  const sum = members.reduce((acc, m) => acc + m.percentage, 0);
  const roundedSum = Math.round(sum * 100) / 100;
  const roundedTarget = Math.round(revenueBPercent * 100) / 100;
  const remaining = Math.round((revenueBPercent - sum) * 100) / 100;
  const progressPct = roundedTarget > 0 ? Math.min((roundedSum / roundedTarget) * 100, 100) : 0;

  useEffect(() => {
    const autoGeneratedPrefixes = ['이름', 'Name', '姓名', '멤버', 'Member', '成员'];

    members.forEach((member, index) => {
      const matchedPrefix = autoGeneratedPrefixes.find((prefix) =>
        new RegExp(`^${prefix}\\s+\\d+$`).test(member.name)
      );

      if (!matchedPrefix) {
        return;
      }

      const localizedName = `${t.members.defaultMemberName} ${index + 1}`;

      if (member.name !== localizedName) {
        updateMember(member.id, { name: localizedName });
      }
    });
  }, [members, t.members.defaultMemberName, updateMember]);

  const handleAddMember = () => {
    if (members.length >= 10) {
      toast(t.members.maxMembers);
      return;
    }
    addMember(`${t.members.defaultMemberName} ${members.length + 1}`, 0);
  };

  const handleFillRemaining = () => {
    if (members.length === 0 || remaining <= 0) return;
    const lastMember = members[members.length - 1];
    const newPercent = Math.round((lastMember.percentage + remaining) * 100) / 100;
    updateMember(lastMember.id, { percentage: newPercent });
  };

  return (
    <Card className="premium-card border-border/40 bg-card">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-foreground">
          <Users className="size-4 text-muted-foreground" />
          {t.members.title}
        </CardTitle>
        <CardAction>
          <Button
            size="sm"
            className="rounded-full bg-brand-red text-white shadow-sm transition-all hover:bg-brand-red/80 active:scale-95"
            onClick={handleAddMember}
          >
            <Plus className="mr-1 size-3.5" />
            {t.members.addMember}
          </Button>
        </CardAction>
      </CardHeader>
      <CardContent className="flex flex-col gap-3">
        {/* Revenue A/B split with visual bar */}
        <div className="space-y-2 rounded-xl border border-brand-gold/10 bg-surface/50 px-3 py-3">
          <div className="flex flex-wrap items-center gap-2">
            <span className="shrink-0 text-sm text-muted-foreground">
              {t.result.revenueA}:
            </span>
            <Input
              type="number"
              inputMode="decimal"
              min={0}
              max={100}
              value={revenueAPercent}
              onChange={(e) =>
                setRevenueAPercent(parseFloat(e.target.value) || 0)
              }
              className="h-8 w-16 border-brand-gold/20 bg-surface text-center tabular-nums text-foreground focus-glow"
            />
            <span className="text-sm text-muted-foreground">%</span>
            <span className="text-sm text-muted-foreground/70">|</span>
            <span className="whitespace-nowrap text-sm text-muted-foreground">
              {t.result.revenueB}: {revenueBPercent}%
            </span>
          </div>
          {/* Visual split bar */}
          <div className="flex h-2 overflow-hidden rounded-full">
            <div
              className="bg-brand-red/70 transition-all duration-300"
              style={{ width: `${revenueAPercent}%` }}
            />
            <div
              className="bg-brand-gold/50 transition-all duration-300"
              style={{ width: `${revenueBPercent}%` }}
            />
          </div>
        </div>

        {/* Member list */}
        {members.map((member) => {
          const withinBPercent = revenueBPercent > 0
            ? Math.round((member.percentage / revenueBPercent) * 10000) / 100
            : 0;

          return (
            <div key={member.id} className="slide-in group space-y-1 rounded-xl border border-border/30 bg-surface/30 p-3 transition-colors hover:border-border/50">
              <div className="flex flex-wrap items-center gap-2">
                <UserCircle className="size-5 shrink-0 text-muted-foreground/70" />
                <Input
                  className="min-w-[120px] flex-1 border-border/40 bg-surface text-foreground focus-glow"
                  placeholder={t.members.memberName}
                  value={member.name}
                  onChange={(e) =>
                    updateMember(member.id, { name: e.target.value })
                  }
                />
                <div className="flex items-center gap-2">
                  <Input
                    className="w-20 border-border/40 bg-surface text-right tabular-nums text-foreground focus-glow"
                    type="number"
                    inputMode="decimal"
                    min={0}
                    max={100}
                    step={0.01}
                    value={member.percentage}
                    onChange={(e) =>
                      updateMember(member.id, {
                        percentage: parseFloat(e.target.value) || 0,
                      })
                    }
                  />
                  <span className="text-sm text-muted-foreground">%</span>
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    disabled={members.length <= 1}
                    onClick={() => removeMember(member.id)}
                    aria-label={t.members.removeMember}
                    className="text-muted-foreground/70 opacity-0 transition-all hover:text-brand-red group-hover:opacity-100"
                  >
                    <X className="size-3.5" />
                  </Button>
                </div>
              </div>
              {member.percentage > 0 && revenueBPercent > 0 && (
                <div className="ml-7 flex items-center gap-1.5 text-xs">
                  <span className="font-medium tabular-nums text-brand-gold/80">
                    {t.result.revenueB} {withinBPercent}%
                  </span>
                  <span className="tabular-nums text-muted-foreground">
                    ({member.percentage}/{revenueBPercent})
                  </span>
                </div>
              )}
            </div>
          );
        })}

        {/* Progress bar + summary */}
        <div className="mt-1 space-y-2 border-t border-border/20 pt-3">
          <div className="h-1.5 overflow-hidden rounded-full bg-surface">
            <div
              className={`h-full rounded-full transition-all duration-500 ${
                roundedSum === roundedTarget ? 'bg-brand-gold' : 'bg-brand-red/60'
              }`}
              style={{ width: `${progressPct}%` }}
            />
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">{t.members.sumLabel}</span>
              {remaining > 0 && members.length > 0 && (
                <Button
                  type="button"
                  variant="outline"
                  size="xs"
                  className="rounded-full border-brand-gold/30 text-brand-gold/80 text-xs transition-all hover:border-brand-gold/50 hover:bg-brand-gold/5 hover:text-brand-gold"
                  onClick={handleFillRemaining}
                >
                  +{remaining}%
                </Button>
              )}
            </div>
            <span
              className={
                roundedSum === roundedTarget
                  ? 'font-bold tabular-nums text-brand-gold'
                  : 'font-bold tabular-nums text-brand-red'
              }
            >
              {roundedSum}% / {roundedTarget}%
            </span>
          </div>

          {roundedSum !== roundedTarget && (
            <p className="text-sm text-brand-red">{t.members.sumError}</p>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
