'use client';

import { useEffect } from 'react';
import { useTranslation } from '@/i18n';
import { useSettlementStore } from '@/lib/store';
import { Card, CardHeader, CardTitle, CardAction, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';

export function MemberManager() {
  const { t } = useTranslation();
  const members = useSettlementStore((s) => s.members);
  const revenueAPercent = useSettlementStore((s) => s.revenueAPercent);
  const setRevenueAPercent = useSettlementStore((s) => s.setRevenueAPercent);
  const addMember = useSettlementStore((s) => s.addMember);
  const removeMember = useSettlementStore((s) => s.removeMember);
  const updateMember = useSettlementStore((s) => s.updateMember);

  const revenueBPercent = 100 - revenueAPercent;
  const sum = members.reduce((acc, m) => acc + m.percentage, 0);
  const roundedSum = Math.round(sum * 100) / 100;
  const roundedTarget = Math.round(revenueBPercent * 100) / 100;
  const remaining = Math.round((revenueBPercent - sum) * 100) / 100;

  useEffect(() => {
    const autoGeneratedPrefixes = ['이름', 'Name', '姓名', '멤버', 'Member', '成员'];

    members.forEach((member, index) => {
      const matchedPrefix = autoGeneratedPrefixes.find((prefix) =>
        new RegExp(`^${prefix}\\s+\\d+$`).test(member.name)
      );

      if (!matchedPrefix) {
        return;
      }

      const localizedName = `${t.members.defaultMemberName} ${index + 1}`;

      if (member.name !== localizedName) {
        updateMember(member.id, { name: localizedName });
      }
    });
  }, [members, t.members.defaultMemberName, updateMember]);

  const handleAddMember = () => {
    if (members.length >= 10) {
      toast(t.members.maxMembers);
      return;
    }
    addMember(`${t.members.defaultMemberName} ${members.length + 1}`, 0);
  };

  const handleFillRemaining = () => {
    if (members.length === 0 || remaining <= 0) return;
    const lastMember = members[members.length - 1];
    const newPercent = Math.round((lastMember.percentage + remaining) * 100) / 100;
    updateMember(lastMember.id, { percentage: newPercent });
  };

  return (
    <Card className="border-border/60 bg-card">
      <CardHeader>
        <CardTitle className="text-brand-gold">{t.members.title}</CardTitle>
        <CardAction>
          <Button
            size="sm"
            className="bg-brand-red text-white hover:bg-brand-red/80"
            onClick={handleAddMember}
          >
            + {t.members.addMember}
          </Button>
        </CardAction>
      </CardHeader>
      <CardContent className="flex flex-col gap-3">
        <div className="flex flex-wrap items-center gap-2 rounded-lg border border-brand-gold/10 bg-surface px-3 py-2">
          <span className="shrink-0 text-sm text-muted-foreground">
            {t.result.revenueA}:
          </span>
          <Input
            type="number"
            inputMode="decimal"
            min={0}
            max={100}
            value={revenueAPercent}
            onChange={(e) =>
              setRevenueAPercent(parseFloat(e.target.value) || 0)
            }
            className="h-8 w-16 border-brand-gold/30 bg-secondary text-center tabular-nums text-foreground focus-visible:ring-1 focus-visible:ring-brand-red/60"
          />
          <span className="text-sm text-muted-foreground">%</span>
          <span className="text-sm text-muted-foreground/40">|</span>
          <span className="whitespace-nowrap text-sm text-muted-foreground">
            {t.result.revenueB}: {revenueBPercent}%
          </span>
        </div>

        {members.map((member) => {
          const withinBPercent = revenueBPercent > 0
            ? Math.round((member.percentage / revenueBPercent) * 10000) / 100
            : 0;

          return (
            <div key={member.id} className="space-y-1">
              <div className="flex flex-wrap items-center gap-2">
                <Input
                  className="min-w-[120px] flex-1 border-border/60 bg-secondary text-foreground focus-visible:ring-2 focus-visible:ring-brand-red/60"
                  placeholder={t.members.memberName}
                  value={member.name}
                  onChange={(e) =>
                    updateMember(member.id, { name: e.target.value })
                  }
                />
                <div className="flex items-center gap-2">
                  <Input
                    className="w-20 border-border/60 bg-secondary text-right tabular-nums text-foreground focus-visible:ring-2 focus-visible:ring-brand-red/60"
                    type="number"
                    inputMode="decimal"
                    min={0}
                    max={100}
                    step={0.01}
                    value={member.percentage}
                    onChange={(e) =>
                      updateMember(member.id, {
                        percentage: parseFloat(e.target.value) || 0,
                      })
                    }
                  />
                  <span className="text-sm text-muted-foreground">%</span>
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    disabled={members.length <= 1}
                    onClick={() => removeMember(member.id)}
                    aria-label={t.members.removeMember}
                    className="text-muted-foreground hover:text-brand-red"
                  >
                    ✕
                  </Button>
                </div>
              </div>
              {member.percentage > 0 && revenueBPercent > 0 && (
                <div className="ml-1 text-[11px] tabular-nums text-muted-foreground/60">
                  → {t.result.revenueB} {withinBPercent}%
                  <span className="ml-1.5 text-muted-foreground/40">
                    ({member.percentage}/{revenueBPercent}×100)
                  </span>
                </div>
              )}
            </div>
          );
        })}

        <div className="mt-2 flex items-center justify-between border-t border-border/40 pt-3">
          <div className="flex items-center gap-2">
            <span className="text-sm text-muted-foreground">{t.members.sumLabel}</span>
            {remaining > 0 && members.length > 0 && (
              <Button
                type="button"
                variant="outline"
                size="xs"
                className="border-brand-gold/20 text-brand-gold/60 hover:bg-brand-gold/10 hover:text-brand-gold text-[10px]"
                onClick={handleFillRemaining}
              >
                +{remaining}%
              </Button>
            )}
          </div>
          <span
            className={
              roundedSum === roundedTarget
                ? 'font-bold tabular-nums text-brand-gold'
                : 'font-bold tabular-nums text-brand-red'
            }
          >
            {roundedSum}% / {roundedTarget}%
          </span>
        </div>

        {roundedSum !== roundedTarget && (
          <p className="text-sm text-brand-red">{t.members.sumError}</p>
        )}
      </CardContent>
    </Card>
  );
}
