'use client';

import { useEffect, useState, useCallback } from 'react';
import { Users, Plus, X, UserCircle, ToggleLeft, ToggleRight } from 'lucide-react';
import { useTranslation } from '@/i18n';
import { useSettlementStore } from '@/lib/store';
import { deriveRevenueAPercentFromRate } from '@/lib/calculator';
import { Card, CardHeader, CardTitle, CardAction, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';

function clampPercent(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.max(0, Math.min(100, value));
}

export function MemberManager() {
  const { t } = useTranslation();
  const members = useSettlementStore((s) => s.members);
  const revenueAPercent = useSettlementStore((s) => s.revenueAPercent);
  const autoRevenueSplitFromRate = useSettlementStore((s) => s.autoRevenueSplitFromRate);
  const inlineFxRate = useSettlementStore((s) => s.inlineFxRate);
  const setRevenueAPercent = useSettlementStore((s) => s.setRevenueAPercent);
  const setAutoRevenueSplitFromRate = useSettlementStore((s) => s.setAutoRevenueSplitFromRate);
  const addMember = useSettlementStore((s) => s.addMember);
  const removeMember = useSettlementStore((s) => s.removeMember);
  const updateMember = useSettlementStore((s) => s.updateMember);

  const effectiveRevenueAPercent = autoRevenueSplitFromRate && inlineFxRate > 0
    ? deriveRevenueAPercentFromRate(inlineFxRate)
    : revenueAPercent;
  const revenueBPercent = Math.round((100 - effectiveRevenueAPercent) * 100) / 100;
  const sum = members.reduce((acc, m) => acc + m.percentage, 0);
  const roundedSum = Math.round(sum * 100) / 100;
  const roundedTarget = Math.round(revenueBPercent * 100) / 100;
  const remaining = Math.round((revenueBPercent - sum) * 100) / 100;
  const progressPct = roundedTarget > 0 ? Math.min((roundedSum / roundedTarget) * 100, 100) : 0;

  // Revenue A percentage input focus state
  const [revenueAFocused, setRevenueAFocused] = useState(false);
  const [revenueALocal, setRevenueALocal] = useState('');

  const handleRevenueAFocus = useCallback(() => {
    setRevenueAFocused(true);
    setRevenueALocal(effectiveRevenueAPercent === 0 ? '' : String(effectiveRevenueAPercent));
  }, [effectiveRevenueAPercent]);

  const handleRevenueABlur = useCallback(() => {
    setRevenueAFocused(false);
    setRevenueALocal('');
  }, []);

  const handleRevenueAChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const nextPercent = clampPercent(parseFloat(e.target.value));
    setRevenueALocal(e.target.value === '' ? '' : String(nextPercent));
    setRevenueAPercent(nextPercent);
  }, [setRevenueAPercent]);

  // Member percentage focus state
  const [focusedMemberId, setFocusedMemberId] = useState<string | null>(null);
  const [memberPercentLocal, setMemberPercentLocal] = useState('');

  // Auto-fill single member's percentage to match revenue B,
  // but only when no member input is focused (so user edits aren't clobbered)
  useEffect(() => {
    if (focusedMemberId !== null) return;
    if (members.length === 1 && revenueBPercent > 0) {
      const member = members[0];
      const target = Math.round(revenueBPercent * 100) / 100;
      if (member.percentage !== target) {
        updateMember(member.id, { percentage: target });
      }
    }
  }, [focusedMemberId, members, revenueBPercent, updateMember]);

  useEffect(() => {
    const autoGeneratedPrefixes = ['이름', 'Name', '姓名', '멤버', 'Member', '成员'];

    members.forEach((member, index) => {
      const matchedPrefix = autoGeneratedPrefixes.find((prefix) =>
        new RegExp(`^${prefix}\\s+\\d+$`).test(member.name)
      );

      if (!matchedPrefix) {
        return;
      }

      const localizedName = `${t.members.defaultMemberName} ${index + 1}`;

      if (member.name !== localizedName) {
        updateMember(member.id, { name: localizedName });
      }
    });
  }, [members, t.members.defaultMemberName, updateMember]);

  const handleAddMember = () => {
    if (members.length >= 10) {
      toast(t.members.maxMembers);
      return;
    }
    addMember(`${t.members.defaultMemberName} ${members.length + 1}`, 0);
  };

  const handleFillRemaining = () => {
    if (members.length === 0 || remaining <= 0) return;
    const lastMember = members[members.length - 1];
    const newPercent = Math.round((lastMember.percentage + remaining) * 100) / 100;
    updateMember(lastMember.id, { percentage: newPercent });
  };

  return (
    <Card className="premium-card border-border/40 bg-card">
      <CardHeader>
        <div className="flex flex-wrap items-center gap-3">
          <CardTitle className="flex items-center gap-2 text-foreground">
            <Users className="size-4 text-muted-foreground" />
            {t.members.title}
          </CardTitle>
          <button
            type="button"
            onClick={() => setAutoRevenueSplitFromRate(!autoRevenueSplitFromRate)}
            className="flex min-h-[32px] items-center gap-1.5 rounded-full border border-border/40 px-3 py-1.5 text-xs transition-colors hover:border-brand-gold/40 hover:bg-brand-gold/5 sm:min-h-0 sm:px-2.5 sm:py-1"
          >
            {autoRevenueSplitFromRate
              ? <ToggleRight className="size-3.5 text-brand-gold" />
              : <ToggleLeft className="size-3.5 text-muted-foreground" />}
            <span className={autoRevenueSplitFromRate ? 'font-medium text-brand-gold' : 'text-muted-foreground'}>
              {t.members.autoFromRate}
            </span>
          </button>
        </div>
        <CardAction>
          <Button
            size="sm"
            className="rounded-full bg-brand-red text-white shadow-sm transition-all hover:bg-brand-red/80 active:scale-95"
            onClick={handleAddMember}
          >
            <Plus className="mr-1 size-3.5" />
            {t.members.addMember}
          </Button>
        </CardAction>
      </CardHeader>
      <CardContent className="flex flex-col gap-3">
        {/* Revenue A/B split with visual bar */}
        <div className="space-y-3 rounded-xl border border-brand-gold/10 bg-surface/50 px-3.5 py-3">
          <div className="flex flex-wrap items-center gap-2.5">
            <span className="inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground">
              <span className="inline-block size-2 rounded-full bg-brand-red/70" aria-hidden />
              {t.result.revenueA}
            </span>
            <div className="flex items-center gap-1 rounded-md border border-brand-gold/20 bg-surface pl-1.5 pr-1 py-0.5">
              <Input
                type="number"
                inputMode="decimal"
                min={0}
                max={100}
                value={revenueAFocused ? revenueALocal : effectiveRevenueAPercent.toFixed(2)}
                onChange={handleRevenueAChange}
                onFocus={handleRevenueAFocus}
                onBlur={handleRevenueABlur}
                disabled={autoRevenueSplitFromRate}
                className="h-9 w-14 border-0 bg-transparent px-0 text-center text-sm font-semibold tabular-nums text-foreground shadow-none focus-glow disabled:cursor-not-allowed disabled:opacity-70 sm:h-7"
              />
              <span className="text-xs font-medium text-muted-foreground">%</span>
            </div>
            <span className="text-muted-foreground/40" aria-hidden>·</span>
            <span className="inline-flex items-center gap-1.5 whitespace-nowrap text-sm font-medium text-muted-foreground">
              <span className="inline-block size-2 rounded-full bg-brand-gold/60" aria-hidden />
              {t.result.revenueB}
              <span className="tabular-nums font-semibold text-foreground">{revenueBPercent.toFixed(2)}%</span>
            </span>
          </div>
          {autoRevenueSplitFromRate && inlineFxRate > 0 && (
            <div className="inline-flex items-center rounded-md border border-brand-gold/15 bg-brand-gold/5 px-2 py-1 font-mono text-[11px] leading-none tabular-nums text-muted-foreground">
              <span>100 − 100 ÷ {inlineFxRate} × 100</span>
              <span className="mx-1.5 text-muted-foreground/40">=</span>
              <span className="font-semibold text-brand-gold">{revenueBPercent.toFixed(2)}%</span>
            </div>
          )}
          {/* Visual split bar */}
          <div className="flex items-center gap-2">
            <span className="w-7 shrink-0 text-[10px] font-bold uppercase tracking-wider text-brand-red/80">A</span>
            <div className="flex h-2.5 flex-1 overflow-hidden rounded-full bg-surface ring-1 ring-inset ring-border/30">
              <div
                className="bg-gradient-to-r from-brand-red/80 to-brand-red/60 transition-all duration-500"
                style={{ width: `${clampPercent(effectiveRevenueAPercent)}%` }}
              />
              <div
                className="bg-gradient-to-r from-brand-gold/60 to-brand-gold/40 transition-all duration-500"
                style={{ width: `${clampPercent(revenueBPercent)}%` }}
              />
            </div>
            <span className="w-7 shrink-0 text-right text-[10px] font-bold uppercase tracking-wider text-brand-gold/80">B</span>
          </div>
        </div>

        {/* Member list */}
        {members.map((member) => {
          const withinBPercent = revenueBPercent > 0
            ? Math.round((member.percentage / revenueBPercent) * 10000) / 100
            : 0;

          return (
            <div key={member.id} className="slide-in group space-y-1.5 rounded-xl border border-border/30 bg-surface/30 p-3 transition-all hover:border-brand-gold/25 hover:bg-surface/50">
              <div className="flex items-center gap-2">
                <UserCircle className="size-5 shrink-0 text-muted-foreground/70 transition-colors group-hover:text-brand-gold/70" />
                <Input
                  className="h-11 min-w-0 flex-1 border-border/40 bg-surface text-sm font-medium text-foreground focus-glow sm:h-9 sm:min-w-[120px]"
                  placeholder={t.members.memberName}
                  value={member.name}
                  onChange={(e) =>
                    updateMember(member.id, { name: e.target.value })
                  }
                />
                <div className="flex shrink-0 items-center gap-1">
                  <div className="flex items-center gap-0.5 rounded-md border border-border/40 bg-surface pl-1.5 pr-1 has-[input:focus-visible]:border-brand-gold/50 has-[input:focus-visible]:ring-1 has-[input:focus-visible]:ring-brand-gold/20 transition-colors">
                    <Input
                      className="h-10 w-14 border-0 bg-transparent px-0 text-right text-sm font-semibold tabular-nums text-foreground shadow-none focus-glow sm:h-8 sm:w-16"
                      type="number"
                      inputMode="decimal"
                      min={0}
                      max={100}
                      step={0.01}
                      value={focusedMemberId === member.id ? memberPercentLocal : member.percentage}
                      onFocus={() => {
                        setFocusedMemberId(member.id);
                        setMemberPercentLocal(member.percentage === 0 ? '' : String(member.percentage));
                      }}
                      onBlur={() => {
                        setFocusedMemberId(null);
                        setMemberPercentLocal('');
                      }}
                      onChange={(e) => {
                        const nextPercent = clampPercent(parseFloat(e.target.value));
                        setMemberPercentLocal(e.target.value === '' ? '' : String(nextPercent));
                        updateMember(member.id, {
                          percentage: nextPercent,
                        });
                      }}
                    />
                    <span className="text-xs font-medium text-muted-foreground">%</span>
                  </div>
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    disabled={false}
                    onClick={() => removeMember(member.id)}
                    aria-label={t.members.removeMember}
                    className="size-9 rounded-full text-muted-foreground/60 opacity-100 transition-all duration-200 hover:bg-brand-red/10 hover:text-brand-red focus-visible:opacity-100 active:scale-90 sm:size-7 sm:opacity-0 sm:group-hover:opacity-100"
                  >
                    <X className="size-4 sm:size-3.5" />
                  </Button>
                </div>
              </div>
              {member.percentage > 0 && revenueBPercent > 0 && (
                <div className="ml-7 flex flex-wrap items-center gap-1.5 text-xs">
                  <span className="rounded-sm bg-brand-gold/10 px-1.5 py-0.5 font-semibold tabular-nums text-brand-gold">
                    {t.result.revenueB} {withinBPercent}%
                  </span>
                  <span className="tabular-nums text-muted-foreground/80">
                    ({member.percentage}/{revenueBPercent})
                  </span>
                </div>
              )}
            </div>
          );
        })}

        {/* Progress bar + summary */}
        <div className="mt-1 space-y-3 border-t border-border/20 pt-3 sm:space-y-2.5">
          <div className="h-2 overflow-hidden rounded-full bg-surface ring-1 ring-inset ring-border/20">
            <div
              className={`h-full rounded-full transition-all duration-500 ${
                roundedSum === roundedTarget
                  ? 'bg-gradient-to-r from-brand-gold/80 to-brand-gold'
                  : 'bg-gradient-to-r from-brand-red/50 to-brand-red/70'
              }`}
              style={{ width: `${progressPct}%` }}
            />
          </div>
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <span className="text-sm font-medium text-muted-foreground">{t.members.sumLabel}</span>
              {remaining > 0 && members.length > 0 && (
                <Button
                  type="button"
                  variant="outline"
                  size="xs"
                  className="h-7 rounded-full border-brand-gold/30 bg-brand-gold/5 px-2.5 text-xs font-semibold tabular-nums text-brand-gold/90 transition-all hover:border-brand-gold/60 hover:bg-brand-gold/10 hover:text-brand-gold active:scale-95 sm:h-6 sm:px-2"
                  onClick={handleFillRemaining}
                >
                  +{remaining}%
                </Button>
              )}
            </div>
            <span
              className={
                roundedSum === roundedTarget
                  ? 'text-base font-bold tabular-nums text-brand-gold'
                  : 'text-base font-bold tabular-nums text-brand-red'
              }
            >
              {roundedSum}% <span className="text-muted-foreground/50">/</span> {roundedTarget}%
            </span>
          </div>

          {roundedSum !== roundedTarget && (
            <div
              role="alert"
              className="flex items-start gap-2 rounded-lg border border-brand-red/25 bg-brand-red/5 px-3 py-2"
            >
              <span
                aria-hidden
                className="mt-0.5 flex size-4 shrink-0 items-center justify-center rounded-full bg-brand-red/15 text-[11px] font-bold leading-none text-brand-red"
              >
                !
              </span>
              <p className="text-xs font-medium leading-relaxed text-brand-red">
                {t.members.sumError}
              </p>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
